### ISSUE TITLE
Symfony3 compatibility 

### ISSUE THREAD

**Issue by gadelkareem** [dariuszwrzesien/DwrAvatarBundle#23]
Any plans to have this bundle compatible with Symfony3?

**Comment by dariuszwrzesien** [comment]
Thank you  for the interest.
Yep, will do it in the next available time.
Let you know when ready

**Comment by dariuszwrzesien** [comment]
Support for Symfony 3 has been added.
In order to use it into sf3 application please use tag: 2.0 like below:
- in your composer.json:
{
    "require": {
        "dwr/avatar-bundle": "2.0"
    }
}
You can still use DwrAvatarBundle in Symfony 2 application by:
- in your composer.json:
{
    "require": {
        "dwr/avatar-bundle": "1.0"
    }
}
